### ISSUE TITLE
Git version update 

### ISSUE THREAD

**Issue by rslid** [cytopia/docker-php-fpm-5.6#30]
Hello,

As centos 7 come with git 1.8 are you open to update with simple compile from source to 2.14.3 ? It just seems too far behind and lacks a lot of features. I have already implemented it but I'm not sure do you want to keep it in this way for particular reason?

**Comment by cytopia** [comment]
@rslid all PHP Docker images are currently in a redesign process.
I will take this into account and will provide the latest git version.
This will however take me another 2-3 weeks until all of them will be fixed and pushed to github.

**Comment by rslid** [comment]
Awesome, thanks a lot! Also I want to say another one big thanks for this tool, it is really convenient and saves a lot of time. 

I've opened a PR request just in case someone needs the latest git now before you publish the redesigned containers as I'm not sure how to "share" these changes without PR (I don't have a lot of experience here with open source projects but I will work in this direction). I don't think it is the best approach but it is definitely working one, feel free to simply reject it.

Regards

**Comment by cytopia** [comment]
Thanks for the help. Merged. Please also check the comment in the PR for info about:

https://github.com/devilbox/docker-php-fpm-7.3
