### ISSUE TITLE
request getting later versions of php-fpm-5.6.31 ? like php-5.6.35-fpm ?

### ISSUE THREAD

**Issue by alzen8work** [cytopia/docker-php-fpm-5.6#33]
currently at our production we are using php 5.6.33 on bare metal (centos7), was planning on using docker-devilbox way, just wondering whether is it possible to get latest patch of php 5.6? perhaps like php-5.6.35-fpm?

**Comment by cytopia** [comment]
This repository will become deprecated soon. There is already a successor, which builds itself every night automatically and always has the very latest version.

Documentation for that repository is not yet finished, but it is fully usable. So please switch to the new one: https://github.com/devilbox/docker-php-fpm

I will make it official in the coming days/weeks.

**Comment by alzen8work** [comment]
Thanks for the fast respond, awesome! looking forward on that new repo... keep me posted ya ! ;-)
